# Site settings
title: Jon Rutishauser's Blog
email: jrutishauser@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Jon. This is where I’ll blog (and likely complain) as I learn JS, HTML, CSS and generally unravel the mysteries of the internets. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jonrutis
github_username:  jrutishauser

# Build settings
markdown: kramdown
